name: Terraform Destroy (Manual)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type DESTROY to confirm"
        required: true

env:
  AWS_REGION: us-east-1

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ "${{ github.event.inputs.confirm }}" != "DESTROY" ]; then
            echo "You must type DESTROY to proceed."; exit 1; fi
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init -input=false
      - run: terraform destroy -auto-approve -input=false
